apiVersion: v1
kind: ConfigMap
metadata:
  name: url-shortener-config

data:
  APP_ENV: "production"
  DATABASE_URL: "postgresql+asyncpg://postgres:postgres@postgresql:5432/urlshortener"
  REDIS_URL: "redis://redis:6379/0"
  KEYCLOAK_URL: "http://keycloak:8081"
  KEYCLOAK_REALM: "url-shortener-realm"
  KEYCLOAK_CLIENT_ID: "url-shortener-client"
